//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_WebService.SkolaWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SkolaTridy", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class SkolaTridy : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NazevField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TridniField;
        
        private System.DateTime ZmenenoKdyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZmenenoKdoField;
        
        private System.Nullable<int> RocnikField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nazev {
            get {
                return this.NazevField;
            }
            set {
                if ((object.ReferenceEquals(this.NazevField, value) != true)) {
                    this.NazevField = value;
                    this.RaisePropertyChanged("Nazev");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Tridni {
            get {
                return this.TridniField;
            }
            set {
                if ((object.ReferenceEquals(this.TridniField, value) != true)) {
                    this.TridniField = value;
                    this.RaisePropertyChanged("Tridni");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime ZmenenoKdy {
            get {
                return this.ZmenenoKdyField;
            }
            set {
                if ((this.ZmenenoKdyField.Equals(value) != true)) {
                    this.ZmenenoKdyField = value;
                    this.RaisePropertyChanged("ZmenenoKdy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ZmenenoKdo {
            get {
                return this.ZmenenoKdoField;
            }
            set {
                if ((object.ReferenceEquals(this.ZmenenoKdoField, value) != true)) {
                    this.ZmenenoKdoField = value;
                    this.RaisePropertyChanged("ZmenenoKdo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<int> Rocnik {
            get {
                return this.RocnikField;
            }
            set {
                if ((this.RocnikField.Equals(value) != true)) {
                    this.RocnikField = value;
                    this.RaisePropertyChanged("Rocnik");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ZakModel", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ZakModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JmenoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrijmeniField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RodneCisloField;
        
        private System.Nullable<bool> MuzField;
        
        private System.Nullable<System.Guid> TridaField;
        
        private bool StudujeField;
        
        private System.DateTime ZmenenoKdyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZmenenoKdoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Jmeno {
            get {
                return this.JmenoField;
            }
            set {
                if ((object.ReferenceEquals(this.JmenoField, value) != true)) {
                    this.JmenoField = value;
                    this.RaisePropertyChanged("Jmeno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Prijmeni {
            get {
                return this.PrijmeniField;
            }
            set {
                if ((object.ReferenceEquals(this.PrijmeniField, value) != true)) {
                    this.PrijmeniField = value;
                    this.RaisePropertyChanged("Prijmeni");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RodneCislo {
            get {
                return this.RodneCisloField;
            }
            set {
                if ((object.ReferenceEquals(this.RodneCisloField, value) != true)) {
                    this.RodneCisloField = value;
                    this.RaisePropertyChanged("RodneCislo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<bool> Muz {
            get {
                return this.MuzField;
            }
            set {
                if ((this.MuzField.Equals(value) != true)) {
                    this.MuzField = value;
                    this.RaisePropertyChanged("Muz");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<System.Guid> Trida {
            get {
                return this.TridaField;
            }
            set {
                if ((this.TridaField.Equals(value) != true)) {
                    this.TridaField = value;
                    this.RaisePropertyChanged("Trida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public bool Studuje {
            get {
                return this.StudujeField;
            }
            set {
                if ((this.StudujeField.Equals(value) != true)) {
                    this.StudujeField = value;
                    this.RaisePropertyChanged("Studuje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.DateTime ZmenenoKdy {
            get {
                return this.ZmenenoKdyField;
            }
            set {
                if ((this.ZmenenoKdyField.Equals(value) != true)) {
                    this.ZmenenoKdyField = value;
                    this.RaisePropertyChanged("ZmenenoKdy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string ZmenenoKdo {
            get {
                return this.ZmenenoKdoField;
            }
            set {
                if ((object.ReferenceEquals(this.ZmenenoKdoField, value) != true)) {
                    this.ZmenenoKdoField = value;
                    this.RaisePropertyChanged("ZmenenoKdo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PredmetModel", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class PredmetModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PredmetField;
        
        private System.Nullable<bool> PovinnyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Predmet {
            get {
                return this.PredmetField;
            }
            set {
                if ((object.ReferenceEquals(this.PredmetField, value) != true)) {
                    this.PredmetField = value;
                    this.RaisePropertyChanged("Predmet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<bool> Povinny {
            get {
                return this.PovinnyField;
            }
            set {
                if ((this.PovinnyField.Equals(value) != true)) {
                    this.PovinnyField = value;
                    this.RaisePropertyChanged("Povinny");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ZnamkaModel", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ZnamkaModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid IdField;
        
        private decimal ZnamkaField;
        
        private System.Guid ZakField;
        
        private System.Guid PredmetField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal Znamka {
            get {
                return this.ZnamkaField;
            }
            set {
                if ((this.ZnamkaField.Equals(value) != true)) {
                    this.ZnamkaField = value;
                    this.RaisePropertyChanged("Znamka");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Guid Zak {
            get {
                return this.ZakField;
            }
            set {
                if ((this.ZakField.Equals(value) != true)) {
                    this.ZakField = value;
                    this.RaisePropertyChanged("Zak");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Guid Predmet {
            get {
                return this.PredmetField;
            }
            set {
                if ((this.PredmetField.Equals(value) != true)) {
                    this.PredmetField = value;
                    this.RaisePropertyChanged("Predmet");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SkolaWS.SkolaSoap")]
    public interface SkolaSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        MVC_WebService.SkolaWS.HelloWorldResponse HelloWorld(MVC_WebService.SkolaWS.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name Id from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TridaSmazat", ReplyAction="*")]
        MVC_WebService.SkolaWS.TridaSmazatResponse TridaSmazat(MVC_WebService.SkolaWS.TridaSmazatRequest request);
        
        // CODEGEN: Generating message contract since element name TridaListResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TridaList", ReplyAction="*")]
        MVC_WebService.SkolaWS.TridaListResponse TridaList(MVC_WebService.SkolaWS.TridaListRequest request);
        
        // CODEGEN: Generating message contract since element name trida from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TridaCreate", ReplyAction="*")]
        MVC_WebService.SkolaWS.TridaCreateResponse TridaCreate(MVC_WebService.SkolaWS.TridaCreateRequest request);
        
        // CODEGEN: Generating message contract since element name Id from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZaciSmazat", ReplyAction="*")]
        MVC_WebService.SkolaWS.ZaciSmazatResponse ZaciSmazat(MVC_WebService.SkolaWS.ZaciSmazatRequest request);
        
        // CODEGEN: Generating message contract since element name ZaciListResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZaciList", ReplyAction="*")]
        MVC_WebService.SkolaWS.ZaciListResponse ZaciList(MVC_WebService.SkolaWS.ZaciListRequest request);
        
        // CODEGEN: Generating message contract since element name item from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZaciCreate", ReplyAction="*")]
        MVC_WebService.SkolaWS.ZaciCreateResponse ZaciCreate(MVC_WebService.SkolaWS.ZaciCreateRequest request);
        
        // CODEGEN: Generating message contract since element name item from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PredmetCreate", ReplyAction="*")]
        MVC_WebService.SkolaWS.PredmetCreateResponse PredmetCreate(MVC_WebService.SkolaWS.PredmetCreateRequest request);
        
        // CODEGEN: Generating message contract since element name PredmetyListResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PredmetyList", ReplyAction="*")]
        MVC_WebService.SkolaWS.PredmetyListResponse PredmetyList(MVC_WebService.SkolaWS.PredmetyListRequest request);
        
        // CODEGEN: Generating message contract since element name Id from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PredmetyDelete", ReplyAction="*")]
        MVC_WebService.SkolaWS.PredmetyDeleteResponse PredmetyDelete(MVC_WebService.SkolaWS.PredmetyDeleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZnamkaCreate", ReplyAction="*")]
        void ZnamkaCreate(decimal znamkaHodnota, System.Guid zak, System.Guid predmet);
        
        // CODEGEN: Generating message contract since element name id from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZnamkyList", ReplyAction="*")]
        MVC_WebService.SkolaWS.ZnamkyListResponse ZnamkyList(MVC_WebService.SkolaWS.ZnamkyListRequest request);
        
        // CODEGEN: Generating message contract since element name Id from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZnamkaDelete", ReplyAction="*")]
        MVC_WebService.SkolaWS.ZnamkaDeleteResponse ZnamkaDelete(MVC_WebService.SkolaWS.ZnamkaDeleteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public MVC_WebService.SkolaWS.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(MVC_WebService.SkolaWS.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public MVC_WebService.SkolaWS.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(MVC_WebService.SkolaWS.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TridaSmazatRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TridaSmazat", Namespace="http://tempuri.org/", Order=0)]
        public MVC_WebService.SkolaWS.TridaSmazatRequestBody Body;
        
        public TridaSmazatRequest() {
        }
        
        public TridaSmazatRequest(MVC_WebService.SkolaWS.TridaSmazatRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TridaSmazatRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Id;
        
        public TridaSmazatRequestBody() {
        }
        
        public TridaSmazatRequestBody(string Id) {
            this.Id = Id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TridaSmazatResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TridaSmazatResponse", Namespace="http://tempuri.org/", Order=0)]
        public MVC_WebService.SkolaWS.TridaSmazatResponseBody Body;
        
        public TridaSmazatResponse() {
        }
        
        public TridaSmazatResponse(MVC_WebService.SkolaWS.TridaSmazatResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TridaSmazatResponseBody {
        
        public TridaSmazatResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TridaListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TridaList", Namespace="http://tempuri.org/", Order=0)]
        public MVC_WebService.SkolaWS.TridaListRequestBody Body;
        
        public TridaListRequest() {
        }
        
        public TridaListRequest(MVC_WebService.SkolaWS.TridaListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TridaListRequestBody {
        
        public TridaListRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TridaListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TridaListResponse", Namespace="http://tempuri.org/", Order=0)]
        public MVC_WebService.SkolaWS.TridaListResponseBody Body;
        
        public TridaListResponse() {
        }
        
        public TridaListResponse(MVC_WebService.SkolaWS.TridaListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TridaListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MVC_WebService.SkolaWS.SkolaTridy[] TridaListResult;
        
        public TridaListResponseBody() {
        }
        
        public TridaListResponseBody(MVC_WebService.SkolaWS.SkolaTridy[] TridaListResult) {
            this.TridaListResult = TridaListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TridaCreateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TridaCreate", Namespace="http://tempuri.org/", Order=0)]
        public MVC_WebService.SkolaWS.TridaCreateRequestBody Body;
        
        public TridaCreateRequest() {
        }
        
        public TridaCreateRequest(MVC_WebService.SkolaWS.TridaCreateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TridaCreateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MVC_WebService.SkolaWS.SkolaTridy trida;
        
        public TridaCreateRequestBody() {
        }
        
        public TridaCreateRequestBody(MVC_WebService.SkolaWS.SkolaTridy trida) {
            this.trida = trida;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TridaCreateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TridaCreateResponse", Namespace="http://tempuri.org/", Order=0)]
        public MVC_WebService.SkolaWS.TridaCreateResponseBody Body;
        
        public TridaCreateResponse() {
        }
        
        public TridaCreateResponse(MVC_WebService.SkolaWS.TridaCreateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TridaCreateResponseBody {
        
        public TridaCreateResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZaciSmazatRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ZaciSmazat", Namespace="http://tempuri.org/", Order=0)]
        public MVC_WebService.SkolaWS.ZaciSmazatRequestBody Body;
        
        public ZaciSmazatRequest() {
        }
        
        public ZaciSmazatRequest(MVC_WebService.SkolaWS.ZaciSmazatRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ZaciSmazatRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Id;
        
        public ZaciSmazatRequestBody() {
        }
        
        public ZaciSmazatRequestBody(string Id) {
            this.Id = Id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZaciSmazatResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ZaciSmazatResponse", Namespace="http://tempuri.org/", Order=0)]
        public MVC_WebService.SkolaWS.ZaciSmazatResponseBody Body;
        
        public ZaciSmazatResponse() {
        }
        
        public ZaciSmazatResponse(MVC_WebService.SkolaWS.ZaciSmazatResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ZaciSmazatResponseBody {
        
        public ZaciSmazatResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZaciListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ZaciList", Namespace="http://tempuri.org/", Order=0)]
        public MVC_WebService.SkolaWS.ZaciListRequestBody Body;
        
        public ZaciListRequest() {
        }
        
        public ZaciListRequest(MVC_WebService.SkolaWS.ZaciListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ZaciListRequestBody {
        
        public ZaciListRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZaciListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ZaciListResponse", Namespace="http://tempuri.org/", Order=0)]
        public MVC_WebService.SkolaWS.ZaciListResponseBody Body;
        
        public ZaciListResponse() {
        }
        
        public ZaciListResponse(MVC_WebService.SkolaWS.ZaciListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ZaciListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MVC_WebService.SkolaWS.ZakModel[] ZaciListResult;
        
        public ZaciListResponseBody() {
        }
        
        public ZaciListResponseBody(MVC_WebService.SkolaWS.ZakModel[] ZaciListResult) {
            this.ZaciListResult = ZaciListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZaciCreateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ZaciCreate", Namespace="http://tempuri.org/", Order=0)]
        public MVC_WebService.SkolaWS.ZaciCreateRequestBody Body;
        
        public ZaciCreateRequest() {
        }
        
        public ZaciCreateRequest(MVC_WebService.SkolaWS.ZaciCreateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ZaciCreateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MVC_WebService.SkolaWS.ZakModel item;
        
        public ZaciCreateRequestBody() {
        }
        
        public ZaciCreateRequestBody(MVC_WebService.SkolaWS.ZakModel item) {
            this.item = item;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZaciCreateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ZaciCreateResponse", Namespace="http://tempuri.org/", Order=0)]
        public MVC_WebService.SkolaWS.ZaciCreateResponseBody Body;
        
        public ZaciCreateResponse() {
        }
        
        public ZaciCreateResponse(MVC_WebService.SkolaWS.ZaciCreateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ZaciCreateResponseBody {
        
        public ZaciCreateResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PredmetCreateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PredmetCreate", Namespace="http://tempuri.org/", Order=0)]
        public MVC_WebService.SkolaWS.PredmetCreateRequestBody Body;
        
        public PredmetCreateRequest() {
        }
        
        public PredmetCreateRequest(MVC_WebService.SkolaWS.PredmetCreateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PredmetCreateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MVC_WebService.SkolaWS.PredmetModel item;
        
        public PredmetCreateRequestBody() {
        }
        
        public PredmetCreateRequestBody(MVC_WebService.SkolaWS.PredmetModel item) {
            this.item = item;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PredmetCreateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PredmetCreateResponse", Namespace="http://tempuri.org/", Order=0)]
        public MVC_WebService.SkolaWS.PredmetCreateResponseBody Body;
        
        public PredmetCreateResponse() {
        }
        
        public PredmetCreateResponse(MVC_WebService.SkolaWS.PredmetCreateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class PredmetCreateResponseBody {
        
        public PredmetCreateResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PredmetyListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PredmetyList", Namespace="http://tempuri.org/", Order=0)]
        public MVC_WebService.SkolaWS.PredmetyListRequestBody Body;
        
        public PredmetyListRequest() {
        }
        
        public PredmetyListRequest(MVC_WebService.SkolaWS.PredmetyListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class PredmetyListRequestBody {
        
        public PredmetyListRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PredmetyListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PredmetyListResponse", Namespace="http://tempuri.org/", Order=0)]
        public MVC_WebService.SkolaWS.PredmetyListResponseBody Body;
        
        public PredmetyListResponse() {
        }
        
        public PredmetyListResponse(MVC_WebService.SkolaWS.PredmetyListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PredmetyListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MVC_WebService.SkolaWS.PredmetModel[] PredmetyListResult;
        
        public PredmetyListResponseBody() {
        }
        
        public PredmetyListResponseBody(MVC_WebService.SkolaWS.PredmetModel[] PredmetyListResult) {
            this.PredmetyListResult = PredmetyListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PredmetyDeleteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PredmetyDelete", Namespace="http://tempuri.org/", Order=0)]
        public MVC_WebService.SkolaWS.PredmetyDeleteRequestBody Body;
        
        public PredmetyDeleteRequest() {
        }
        
        public PredmetyDeleteRequest(MVC_WebService.SkolaWS.PredmetyDeleteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PredmetyDeleteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Id;
        
        public PredmetyDeleteRequestBody() {
        }
        
        public PredmetyDeleteRequestBody(string Id) {
            this.Id = Id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PredmetyDeleteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PredmetyDeleteResponse", Namespace="http://tempuri.org/", Order=0)]
        public MVC_WebService.SkolaWS.PredmetyDeleteResponseBody Body;
        
        public PredmetyDeleteResponse() {
        }
        
        public PredmetyDeleteResponse(MVC_WebService.SkolaWS.PredmetyDeleteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class PredmetyDeleteResponseBody {
        
        public PredmetyDeleteResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZnamkyListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ZnamkyList", Namespace="http://tempuri.org/", Order=0)]
        public MVC_WebService.SkolaWS.ZnamkyListRequestBody Body;
        
        public ZnamkyListRequest() {
        }
        
        public ZnamkyListRequest(MVC_WebService.SkolaWS.ZnamkyListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ZnamkyListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        public ZnamkyListRequestBody() {
        }
        
        public ZnamkyListRequestBody(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZnamkyListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ZnamkyListResponse", Namespace="http://tempuri.org/", Order=0)]
        public MVC_WebService.SkolaWS.ZnamkyListResponseBody Body;
        
        public ZnamkyListResponse() {
        }
        
        public ZnamkyListResponse(MVC_WebService.SkolaWS.ZnamkyListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ZnamkyListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MVC_WebService.SkolaWS.ZnamkaModel[] ZnamkyListResult;
        
        public ZnamkyListResponseBody() {
        }
        
        public ZnamkyListResponseBody(MVC_WebService.SkolaWS.ZnamkaModel[] ZnamkyListResult) {
            this.ZnamkyListResult = ZnamkyListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZnamkaDeleteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ZnamkaDelete", Namespace="http://tempuri.org/", Order=0)]
        public MVC_WebService.SkolaWS.ZnamkaDeleteRequestBody Body;
        
        public ZnamkaDeleteRequest() {
        }
        
        public ZnamkaDeleteRequest(MVC_WebService.SkolaWS.ZnamkaDeleteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ZnamkaDeleteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Id;
        
        public ZnamkaDeleteRequestBody() {
        }
        
        public ZnamkaDeleteRequestBody(string Id) {
            this.Id = Id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZnamkaDeleteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ZnamkaDeleteResponse", Namespace="http://tempuri.org/", Order=0)]
        public MVC_WebService.SkolaWS.ZnamkaDeleteResponseBody Body;
        
        public ZnamkaDeleteResponse() {
        }
        
        public ZnamkaDeleteResponse(MVC_WebService.SkolaWS.ZnamkaDeleteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ZnamkaDeleteResponseBody {
        
        public ZnamkaDeleteResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SkolaSoapChannel : MVC_WebService.SkolaWS.SkolaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SkolaSoapClient : System.ServiceModel.ClientBase<MVC_WebService.SkolaWS.SkolaSoap>, MVC_WebService.SkolaWS.SkolaSoap {
        
        public SkolaSoapClient() {
        }
        
        public SkolaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SkolaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SkolaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SkolaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MVC_WebService.SkolaWS.HelloWorldResponse MVC_WebService.SkolaWS.SkolaSoap.HelloWorld(MVC_WebService.SkolaWS.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            MVC_WebService.SkolaWS.HelloWorldRequest inValue = new MVC_WebService.SkolaWS.HelloWorldRequest();
            inValue.Body = new MVC_WebService.SkolaWS.HelloWorldRequestBody();
            MVC_WebService.SkolaWS.HelloWorldResponse retVal = ((MVC_WebService.SkolaWS.SkolaSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MVC_WebService.SkolaWS.TridaSmazatResponse MVC_WebService.SkolaWS.SkolaSoap.TridaSmazat(MVC_WebService.SkolaWS.TridaSmazatRequest request) {
            return base.Channel.TridaSmazat(request);
        }
        
        public void TridaSmazat(string Id) {
            MVC_WebService.SkolaWS.TridaSmazatRequest inValue = new MVC_WebService.SkolaWS.TridaSmazatRequest();
            inValue.Body = new MVC_WebService.SkolaWS.TridaSmazatRequestBody();
            inValue.Body.Id = Id;
            MVC_WebService.SkolaWS.TridaSmazatResponse retVal = ((MVC_WebService.SkolaWS.SkolaSoap)(this)).TridaSmazat(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MVC_WebService.SkolaWS.TridaListResponse MVC_WebService.SkolaWS.SkolaSoap.TridaList(MVC_WebService.SkolaWS.TridaListRequest request) {
            return base.Channel.TridaList(request);
        }
        
        public MVC_WebService.SkolaWS.SkolaTridy[] TridaList() {
            MVC_WebService.SkolaWS.TridaListRequest inValue = new MVC_WebService.SkolaWS.TridaListRequest();
            inValue.Body = new MVC_WebService.SkolaWS.TridaListRequestBody();
            MVC_WebService.SkolaWS.TridaListResponse retVal = ((MVC_WebService.SkolaWS.SkolaSoap)(this)).TridaList(inValue);
            return retVal.Body.TridaListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MVC_WebService.SkolaWS.TridaCreateResponse MVC_WebService.SkolaWS.SkolaSoap.TridaCreate(MVC_WebService.SkolaWS.TridaCreateRequest request) {
            return base.Channel.TridaCreate(request);
        }
        
        public void TridaCreate(MVC_WebService.SkolaWS.SkolaTridy trida) {
            MVC_WebService.SkolaWS.TridaCreateRequest inValue = new MVC_WebService.SkolaWS.TridaCreateRequest();
            inValue.Body = new MVC_WebService.SkolaWS.TridaCreateRequestBody();
            inValue.Body.trida = trida;
            MVC_WebService.SkolaWS.TridaCreateResponse retVal = ((MVC_WebService.SkolaWS.SkolaSoap)(this)).TridaCreate(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MVC_WebService.SkolaWS.ZaciSmazatResponse MVC_WebService.SkolaWS.SkolaSoap.ZaciSmazat(MVC_WebService.SkolaWS.ZaciSmazatRequest request) {
            return base.Channel.ZaciSmazat(request);
        }
        
        public void ZaciSmazat(string Id) {
            MVC_WebService.SkolaWS.ZaciSmazatRequest inValue = new MVC_WebService.SkolaWS.ZaciSmazatRequest();
            inValue.Body = new MVC_WebService.SkolaWS.ZaciSmazatRequestBody();
            inValue.Body.Id = Id;
            MVC_WebService.SkolaWS.ZaciSmazatResponse retVal = ((MVC_WebService.SkolaWS.SkolaSoap)(this)).ZaciSmazat(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MVC_WebService.SkolaWS.ZaciListResponse MVC_WebService.SkolaWS.SkolaSoap.ZaciList(MVC_WebService.SkolaWS.ZaciListRequest request) {
            return base.Channel.ZaciList(request);
        }
        
        public MVC_WebService.SkolaWS.ZakModel[] ZaciList() {
            MVC_WebService.SkolaWS.ZaciListRequest inValue = new MVC_WebService.SkolaWS.ZaciListRequest();
            inValue.Body = new MVC_WebService.SkolaWS.ZaciListRequestBody();
            MVC_WebService.SkolaWS.ZaciListResponse retVal = ((MVC_WebService.SkolaWS.SkolaSoap)(this)).ZaciList(inValue);
            return retVal.Body.ZaciListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MVC_WebService.SkolaWS.ZaciCreateResponse MVC_WebService.SkolaWS.SkolaSoap.ZaciCreate(MVC_WebService.SkolaWS.ZaciCreateRequest request) {
            return base.Channel.ZaciCreate(request);
        }
        
        public void ZaciCreate(MVC_WebService.SkolaWS.ZakModel item) {
            MVC_WebService.SkolaWS.ZaciCreateRequest inValue = new MVC_WebService.SkolaWS.ZaciCreateRequest();
            inValue.Body = new MVC_WebService.SkolaWS.ZaciCreateRequestBody();
            inValue.Body.item = item;
            MVC_WebService.SkolaWS.ZaciCreateResponse retVal = ((MVC_WebService.SkolaWS.SkolaSoap)(this)).ZaciCreate(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MVC_WebService.SkolaWS.PredmetCreateResponse MVC_WebService.SkolaWS.SkolaSoap.PredmetCreate(MVC_WebService.SkolaWS.PredmetCreateRequest request) {
            return base.Channel.PredmetCreate(request);
        }
        
        public void PredmetCreate(MVC_WebService.SkolaWS.PredmetModel item) {
            MVC_WebService.SkolaWS.PredmetCreateRequest inValue = new MVC_WebService.SkolaWS.PredmetCreateRequest();
            inValue.Body = new MVC_WebService.SkolaWS.PredmetCreateRequestBody();
            inValue.Body.item = item;
            MVC_WebService.SkolaWS.PredmetCreateResponse retVal = ((MVC_WebService.SkolaWS.SkolaSoap)(this)).PredmetCreate(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MVC_WebService.SkolaWS.PredmetyListResponse MVC_WebService.SkolaWS.SkolaSoap.PredmetyList(MVC_WebService.SkolaWS.PredmetyListRequest request) {
            return base.Channel.PredmetyList(request);
        }
        
        public MVC_WebService.SkolaWS.PredmetModel[] PredmetyList() {
            MVC_WebService.SkolaWS.PredmetyListRequest inValue = new MVC_WebService.SkolaWS.PredmetyListRequest();
            inValue.Body = new MVC_WebService.SkolaWS.PredmetyListRequestBody();
            MVC_WebService.SkolaWS.PredmetyListResponse retVal = ((MVC_WebService.SkolaWS.SkolaSoap)(this)).PredmetyList(inValue);
            return retVal.Body.PredmetyListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MVC_WebService.SkolaWS.PredmetyDeleteResponse MVC_WebService.SkolaWS.SkolaSoap.PredmetyDelete(MVC_WebService.SkolaWS.PredmetyDeleteRequest request) {
            return base.Channel.PredmetyDelete(request);
        }
        
        public void PredmetyDelete(string Id) {
            MVC_WebService.SkolaWS.PredmetyDeleteRequest inValue = new MVC_WebService.SkolaWS.PredmetyDeleteRequest();
            inValue.Body = new MVC_WebService.SkolaWS.PredmetyDeleteRequestBody();
            inValue.Body.Id = Id;
            MVC_WebService.SkolaWS.PredmetyDeleteResponse retVal = ((MVC_WebService.SkolaWS.SkolaSoap)(this)).PredmetyDelete(inValue);
        }
        
        public void ZnamkaCreate(decimal znamkaHodnota, System.Guid zak, System.Guid predmet) {
            base.Channel.ZnamkaCreate(znamkaHodnota, zak, predmet);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MVC_WebService.SkolaWS.ZnamkyListResponse MVC_WebService.SkolaWS.SkolaSoap.ZnamkyList(MVC_WebService.SkolaWS.ZnamkyListRequest request) {
            return base.Channel.ZnamkyList(request);
        }
        
        public MVC_WebService.SkolaWS.ZnamkaModel[] ZnamkyList(string id) {
            MVC_WebService.SkolaWS.ZnamkyListRequest inValue = new MVC_WebService.SkolaWS.ZnamkyListRequest();
            inValue.Body = new MVC_WebService.SkolaWS.ZnamkyListRequestBody();
            inValue.Body.id = id;
            MVC_WebService.SkolaWS.ZnamkyListResponse retVal = ((MVC_WebService.SkolaWS.SkolaSoap)(this)).ZnamkyList(inValue);
            return retVal.Body.ZnamkyListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MVC_WebService.SkolaWS.ZnamkaDeleteResponse MVC_WebService.SkolaWS.SkolaSoap.ZnamkaDelete(MVC_WebService.SkolaWS.ZnamkaDeleteRequest request) {
            return base.Channel.ZnamkaDelete(request);
        }
        
        public void ZnamkaDelete(string Id) {
            MVC_WebService.SkolaWS.ZnamkaDeleteRequest inValue = new MVC_WebService.SkolaWS.ZnamkaDeleteRequest();
            inValue.Body = new MVC_WebService.SkolaWS.ZnamkaDeleteRequestBody();
            inValue.Body.Id = Id;
            MVC_WebService.SkolaWS.ZnamkaDeleteResponse retVal = ((MVC_WebService.SkolaWS.SkolaSoap)(this)).ZnamkaDelete(inValue);
        }
    }
}
